### ISSUE TITLE
Apache 下设置伪静态规则

### ISSUE THREAD

**Issue by KagurazakaShirosatosu** [LoliLin/RSSHub#2]
在 apache 环境下尝试写入以下代码到 `.htaccess` 但出错（HTTP 500）
```
RewriteEngine On
RewriteRule ^(.*)$ /index.php/$1 [L]
```
环境：apache 2.4 + php 7.2

希望能够推出 apache 版的伪静态设置和完善文档~
祝大佬学业顺利（

**Comment by LynMoe** [comment]
在 09c4349c30bd4c1ae3ee459aa53eb6e897f92432 中提交了伪静态文件 ( 从 tp 里抄的

手头没有 apache 环境，也不知道能不能用，还望dalao测试一波
